// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace laboratory_work_12.Models;

public partial class Scientist
{
    public int ScientistId { get; set; }

    public string Name { get; set; }

    public string Specialty { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
}