// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace laboratory_work_11_part_1_TCPServer.Models;

public partial class StockPricesContext : DbContext
{
    public StockPricesContext(DbContextOptions<StockPricesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Price> Prices { get; set; }

    public virtual DbSet<Ticker> Tickers { get; set; }

    public virtual DbSet<TodaysCondition> TodaysConditions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Price>(entity =>
        {
            entity.HasOne(d => d.Ticker).WithMany(p => p.Prices)
                .HasForeignKey(d => d.TickerId)
                .HasConstraintName("FK_Prices_Tickers");
        });

        modelBuilder.Entity<Ticker>(entity =>
        {
            entity.Property(e => e.TickerName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TodaysCondition>(entity =>
        {
            entity.Property(e => e.State)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Ticker).WithMany(p => p.TodaysConditions)
                .HasForeignKey(d => d.TickerId)
                .HasConstraintName("FK_TodaysConditions_Tickers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}