// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace laboratory_work_11_part_1_TCPServer.Models;

public partial class Ticker
{
    public int Id { get; set; }

    public string TickerName { get; set; }

    public virtual ICollection<Price> Prices { get; set; } = new List<Price>();

    public virtual ICollection<TodaysCondition> TodaysConditions { get; set; } = new List<TodaysCondition>();
}