// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace laboratory_work_11_part_1_TCPServer.Models;

public partial class TodaysCondition
{
    public int Id { get; set; }

    public int? TickerId { get; set; }

    public string State { get; set; }

    public virtual Ticker Ticker { get; set; }
}