// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace laboratory_work_13.Models;

public partial class Equipment
{
    public int EquipmentId { get; set; }

    public string Name { get; set; }

    public string Status { get; set; }

    public int? ProjectId { get; set; }

    public virtual Project Project { get; set; }
}