// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace laboratory_work_13.Models;

public partial class ScientificLaboratoryDBContext : DbContext
{
    public ScientificLaboratoryDBContext(DbContextOptions<ScientificLaboratoryDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Equipment> Equipment { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Scientist> Scientists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Equipment>(entity =>
        {
            entity.Property(e => e.Name)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Project).WithMany(p => p.Equipment)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK_Equipment_Projects");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Title)
                .HasMaxLength(200)
                .IsUnicode(false);

            entity.HasOne(d => d.Scientist).WithMany(p => p.Projects)
                .HasForeignKey(d => d.ScientistId)
                .HasConstraintName("FK_Projects_Scientists");
        });

        modelBuilder.Entity<Scientist>(entity =>
        {
            entity.Property(e => e.Email)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Specialty)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}